services:
  game-hub:
    image: niklasedelstam/gamehub
    build:
      context: .
    container_name: game-hub_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    env_file: 
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
      - ./.env:/app/.env
